images:
  - img_id: First image identifier
    vendor_data: First image vendor data
    file_name: First image file name

  - img_id:  Second iamge identifier
    vendor_data: Second image vendor data
    file_name: Second image file name
