images:
  - sub_comp_name: First image identifier
    vendor_data: First image vendor data
    file_name: First image file name

  - sub_comp_name:  Second iamge identifier
    vendor_data: Second image vendor data
    file_name: Second image file name
