name: create-Linux-wheels
run-name: ${{ github.actor }} create_wheels_for_linux
on:
  push:
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  create-wheels-for-manylinux:
      runs-on: ubuntu-22.04
      if: github.repository == 'PelionIoT/manifest-tool'
      steps:
        - uses: actions/checkout@v4
        - run: ./build_manylinux_wheels.sh
        - name: Upload manylinux wheels
          uses: actions/upload-artifact@v3
          with:
            name: wheels
            path: dist/*.*
  create-tar-gz:
      runs-on: ubuntu-22.04
      if: github.repository == 'PelionIoT/manifest-tool'
      steps:
        - uses: actions/checkout@v4
        - run: pip install -r requirements.txt
        - run: pip install build
        - run: python -m build
        - name: Upload .tar.gz -file
          uses: actions/upload-artifact@v3
          with:
            name: wheels
            path: dist/*.tar.gz
  # From internal - do not upload, just build to make sure
  # all is OK.
  create-wheels-for-manylinux-internal:
      runs-on: ubuntu-22.04
      if: github.repository == 'PelionIoT/manifest-tool-internal'
      steps:
        - uses: actions/checkout@v4
        - run: ./build_manylinux_wheels.sh
        - name: Integration with slack
          uses: act10ns/slack@v2
          with:
            status: ${{ job.status }}
            channel: '#testing_build'
          if: failure()
  create-tar-gz-int:
      runs-on: ubuntu-22.04
      if: github.repository == 'PelionIoT/manifest-tool-internal'
      steps:
        - uses: actions/checkout@v4
        - run: pip install -r requirements.txt
        - run: pip install build
        - run: python -m build
        - name: Integration with slack
          uses: act10ns/slack@v2
          with:
            status: ${{ job.status }}
            channel: '#testing_build'
          if: failure()
